### ISSUE TITLE
Problem with old format RMC

### ISSUE THREAD

**Issue by Yaumen** [Emandhal/NMEA0183#2]
Hi! Thank you for yesterday's fix.
A problem was discovered with some RMC frames. Problem with reading FAA mode and Navigation Status.
Some examples (from WIKI):
1) $GPRMC,125504.049,A,5542.2389,N,03741.6063,E,0.06,25.82,200906,,,*17 -> [ERROR]
2) $GPRMC,,V,,,,,,,080907,9.6,E,N*31
3) $GNRMC,131807.00,A,5356.52249,N,02734.00205,E,,,180424,,,A,V*35

**Comment by Emandhal** [comment]
Hi,

I made a fix for these frames.
Thanks for helping to improve the decoding.
I also add these frames examples to the test unit.
